[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
scaas_liquidity = "pqgqKahpG1y2wsgxFhzaAnkV1cL9vk8MSg9qm4q646F"

[programs.devnet]
scaas_liquidity = "9vDwZVJXw5nxymWmUcgmNpemDH5EBcJwLNhtsznrgJDH"

[programs.mainnet]
scaas_liquidity = "pqgqKahpG1y2wsgxFhzaAnkV1cL9vk8MSg9qm4q646F"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#cluster = "mainnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
